"""Turn a filled-in docs/fares-to-fill.xlsx into a migration.

    python3 scripts/import-fares.py path/to/fares.xlsx

Reads the 'Fares to fill' tab: From, To, One way ($), Round trip ($). Every row
with a one-way price becomes a route in the price list (per person, before VAT).
Blank rows are skipped — the office keeps quoting those. Writes the next
numbered file in supabase/migrations/ and prints a summary; review it, then
`supabase db push --linked`.

Refuses, and writes nothing, if a stop isn't on the dock list, a price isn't a
positive number, a round trip has no one-way, or the same pair appears twice.
Needs openpyxl.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "supabase" / "migrations"
API = "https://fjdoaonnoezbbitbawzs.supabase.co/rest/v1"
KEY = "sb_publishable_RjTM-t2isu1Teq9P5z37PQ_h_Oy3EpP"  # the public key, as on the website


def live_docks() -> set[str]:
    req = urllib.request.Request(f"{API}/docks?select=name", headers={"apikey": KEY})
    with urllib.request.urlopen(req) as r:
        return {d["name"] for d in json.load(r)}


def cents(value, where: str) -> int | None:
    if value is None or str(value).strip() == "":
        return None
    try:
        n = float(str(value).replace("$", "").replace(",", "").strip())
    except ValueError:
        raise SystemExit(f"{where}: '{value}' isn't a price")
    if n <= 0:
        raise SystemExit(f"{where}: prices must be above 0")
    return round(n * 100)


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower().replace("ñ", "n")).strip("-")[:40]


def sql(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    ws = load_workbook(sys.argv[1], data_only=True)["Fares to fill"]
    docks = live_docks()

    rows, seen = [], set()
    for i, (frm, to, one, rt, *_) in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        where = f"Row {i} ({frm} → {to})"
        one_c, rt_c = cents(one, where), cents(rt, where)
        if one_c is None and rt_c is None:
            continue
        if one_c is None:
            raise SystemExit(f"{where}: has a round trip but no one-way price")
        for stop in (frm, to):
            if stop not in docks:
                raise SystemExit(f"{where}: '{stop}' isn't on the dock list")
        pair = frozenset((frm, to))
        if pair in seen:
            raise SystemExit(f"{where}: this pair is listed twice")
        seen.add(pair)
        rows.append((frm, to, one_c, rt_c))

    if not rows:
        raise SystemExit("No prices filled in — nothing to do.")

    n = max(int(p.name[:4]) for p in MIGRATIONS.glob("[0-9][0-9][0-9][0-9]_*.sql")) + 1
    out = MIGRATIONS / f"{n:04d}_stop_to_stop_fares.sql"
    values = ",\n".join(
        f"  ({sql('route-' + slug(a) + '--' + slug(b))}, 'route', {sql(b)}, 'per_person', "
        f"{one}, {rt if rt is not None else 'null'}, {sql(a)}, {sql(b)}, {1000 + k})"
        for k, (a, b, one, rt) in enumerate(rows)
    )
    out.write_text(
        f"-- Stop-to-stop fares from Jack's sheet ({Path(sys.argv[1]).name}).\n"
        "-- Per person, before VAT. Generated by scripts/import-fares.py.\n\n"
        "insert into services\n"
        "  (slug, category, title, pricing_model, price_cents, round_trip_cents, from_point, to_point, sort)\n"
        f"values\n{values}\n"
        "on conflict (slug) do update set\n"
        "  price_cents = excluded.price_cents, round_trip_cents = excluded.round_trip_cents,\n"
        "  from_point = excluded.from_point, to_point = excluded.to_point, is_active = true;\n"
    )
    print(f"{len(rows)} fares → {out.relative_to(ROOT)}")
    for a, b, one, rt in rows[:10]:
        print(f"  {a} ↔ {b}: ${one / 100:g}" + (f" / ${rt / 100:g} round trip" if rt else ""))
    if len(rows) > 10:
        print(f"  … and {len(rows) - 10} more")


if __name__ == "__main__":
    main()
