-- Stop-to-stop fares from Jack's sheet (fares to fill v1, 5 Oct 2026: Margaritaville and Carnival).
-- Per person, before VAT. Generated by scripts/import-fares.py.

insert into services
  (slug, category, title, pricing_model, price_cents, round_trip_cents, from_point, to_point, sort)
values
  ('route-paradise-island-margaritaville--paradise-island-carnival', 'route', 'Paradise Island – Carnival', 'per_person', 1000, 1800, 'Paradise Island – Margaritaville', 'Paradise Island – Carnival', 1000),
  ('route-paradise-island-margaritaville--pearl-island', 'route', 'Pearl Island', 'per_person', 3000, 4900, 'Paradise Island – Margaritaville', 'Pearl Island', 1001),
  ('route-paradise-island-margaritaville--floating-bar', 'route', 'Floating Bar', 'per_person', 2500, 4500, 'Paradise Island – Margaritaville', 'Floating Bar', 1002),
  ('route-paradise-island-margaritaville--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 3500, 6000, 'Paradise Island – Margaritaville', 'Blue Lagoon', 1003),
  ('route-paradise-island-margaritaville--senor-frog-s', 'route', 'Señor Frog''s', 'per_person', 1000, 1800, 'Paradise Island – Margaritaville', 'Señor Frog''s', 1004),
  ('route-paradise-island-margaritaville--green-parrot', 'route', 'Green Parrot', 'per_person', 1000, 1800, 'Paradise Island – Margaritaville', 'Green Parrot', 1005),
  ('route-paradise-island-margaritaville--poop-deck', 'route', 'Poop Deck', 'per_person', 1200, 2000, 'Paradise Island – Margaritaville', 'Poop Deck', 1006),
  ('route-paradise-island-margaritaville--fort-montagu', 'route', 'Fort Montagu', 'per_person', 1600, 2800, 'Paradise Island – Margaritaville', 'Fort Montagu', 1007),
  ('route-paradise-island-margaritaville--pigs-beach', 'route', 'Pigs Beach', 'per_person', 2500, 4500, 'Paradise Island – Margaritaville', 'Pigs Beach', 1008),
  ('route-paradise-island-margaritaville--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 3500, 6000, 'Paradise Island – Margaritaville', 'Rose Island – Goodies', 1009),
  ('route-paradise-island-margaritaville--junkanoo-beach', 'route', 'Junkanoo Beach', 'per_person', 1500, 2500, 'Paradise Island – Margaritaville', 'Junkanoo Beach', 1010),
  ('route-paradise-island-margaritaville--arawak-cay-fish-fry', 'route', 'Arawak Cay / Fish Fry', 'per_person', 1500, 2500, 'Paradise Island – Margaritaville', 'Arawak Cay / Fish Fry', 1011),
  ('route-paradise-island-margaritaville--goodman-s-bay', 'route', 'Goodman''s Bay', 'per_person', 3500, 6000, 'Paradise Island – Margaritaville', 'Goodman''s Bay', 1012),
  ('route-paradise-island-margaritaville--breezes', 'route', 'Breezes', 'per_person', 4000, 7000, 'Paradise Island – Margaritaville', 'Breezes', 1013),
  ('route-paradise-island-margaritaville--baha-mar', 'route', 'Baha Mar', 'per_person', 4000, 7000, 'Paradise Island – Margaritaville', 'Baha Mar', 1014),
  ('route-paradise-island-carnival--pearl-island', 'route', 'Pearl Island', 'per_person', 3000, 4900, 'Paradise Island – Carnival', 'Pearl Island', 1015),
  ('route-paradise-island-carnival--floating-bar', 'route', 'Floating Bar', 'per_person', 2500, 4500, 'Paradise Island – Carnival', 'Floating Bar', 1016),
  ('route-paradise-island-carnival--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 3500, 6000, 'Paradise Island – Carnival', 'Blue Lagoon', 1017),
  ('route-paradise-island-carnival--senor-frog-s', 'route', 'Señor Frog''s', 'per_person', 1000, 1800, 'Paradise Island – Carnival', 'Señor Frog''s', 1018),
  ('route-paradise-island-carnival--green-parrot', 'route', 'Green Parrot', 'per_person', 1000, 1800, 'Paradise Island – Carnival', 'Green Parrot', 1019),
  ('route-paradise-island-carnival--poop-deck', 'route', 'Poop Deck', 'per_person', 1200, 2000, 'Paradise Island – Carnival', 'Poop Deck', 1020),
  ('route-paradise-island-carnival--fort-montagu', 'route', 'Fort Montagu', 'per_person', 1600, 2800, 'Paradise Island – Carnival', 'Fort Montagu', 1021),
  ('route-paradise-island-carnival--pigs-beach', 'route', 'Pigs Beach', 'per_person', 2500, 4500, 'Paradise Island – Carnival', 'Pigs Beach', 1022),
  ('route-paradise-island-carnival--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 3500, 6000, 'Paradise Island – Carnival', 'Rose Island – Goodies', 1023),
  ('route-paradise-island-carnival--junkanoo-beach', 'route', 'Junkanoo Beach', 'per_person', 1500, 2500, 'Paradise Island – Carnival', 'Junkanoo Beach', 1024),
  ('route-paradise-island-carnival--arawak-cay-fish-fry', 'route', 'Arawak Cay / Fish Fry', 'per_person', 1500, 2500, 'Paradise Island – Carnival', 'Arawak Cay / Fish Fry', 1025),
  ('route-paradise-island-carnival--goodman-s-bay', 'route', 'Goodman''s Bay', 'per_person', 3500, 6000, 'Paradise Island – Carnival', 'Goodman''s Bay', 1026),
  ('route-paradise-island-carnival--breezes', 'route', 'Breezes', 'per_person', 4000, 7000, 'Paradise Island – Carnival', 'Breezes', 1027),
  ('route-paradise-island-carnival--baha-mar', 'route', 'Baha Mar', 'per_person', 4000, 7000, 'Paradise Island – Carnival', 'Baha Mar', 1028)
on conflict (slug) do update set
  price_cents = excluded.price_cents, round_trip_cents = excluded.round_trip_cents,
  from_point = excluded.from_point, to_point = excluded.to_point, is_active = true;
