-- Stop-to-stop fares from Jack's sheet (fares to fill v3, 5 Oct 2026: Señor Frog's, Green Parrot, Poop Deck; Poop Deck ↔ Fort Montagu held for a check).
-- Per person, before VAT. Generated by scripts/import-fares.py.

insert into services
  (slug, category, title, pricing_model, price_cents, round_trip_cents, from_point, to_point, sort)
values
  ('route-senor-frog-s--green-parrot', 'route', 'Green Parrot', 'per_person', 1000, 1800, 'Señor Frog''s', 'Green Parrot', 1000),
  ('route-senor-frog-s--poop-deck', 'route', 'Poop Deck', 'per_person', 1200, 2000, 'Señor Frog''s', 'Poop Deck', 1001),
  ('route-senor-frog-s--fort-montagu', 'route', 'Fort Montagu', 'per_person', 1600, 2800, 'Señor Frog''s', 'Fort Montagu', 1002),
  ('route-senor-frog-s--pigs-beach', 'route', 'Pigs Beach', 'per_person', 2500, 4500, 'Señor Frog''s', 'Pigs Beach', 1003),
  ('route-senor-frog-s--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 3500, 6000, 'Señor Frog''s', 'Rose Island – Goodies', 1004),
  ('route-senor-frog-s--junkanoo-beach', 'route', 'Junkanoo Beach', 'per_person', 1000, 1800, 'Señor Frog''s', 'Junkanoo Beach', 1005),
  ('route-senor-frog-s--arawak-cay-fish-fry', 'route', 'Arawak Cay / Fish Fry', 'per_person', 1500, 2500, 'Señor Frog''s', 'Arawak Cay / Fish Fry', 1006),
  ('route-senor-frog-s--goodman-s-bay', 'route', 'Goodman''s Bay', 'per_person', 3500, 6000, 'Señor Frog''s', 'Goodman''s Bay', 1007),
  ('route-senor-frog-s--breezes', 'route', 'Breezes', 'per_person', 4000, 7000, 'Señor Frog''s', 'Breezes', 1008),
  ('route-senor-frog-s--baha-mar', 'route', 'Baha Mar', 'per_person', 4000, 7000, 'Señor Frog''s', 'Baha Mar', 1009),
  ('route-green-parrot--poop-deck', 'route', 'Poop Deck', 'per_person', 1000, 1800, 'Green Parrot', 'Poop Deck', 1010),
  ('route-green-parrot--fort-montagu', 'route', 'Fort Montagu', 'per_person', 1200, 2000, 'Green Parrot', 'Fort Montagu', 1011),
  ('route-green-parrot--pigs-beach', 'route', 'Pigs Beach', 'per_person', 2500, 4500, 'Green Parrot', 'Pigs Beach', 1012),
  ('route-green-parrot--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 3500, 6000, 'Green Parrot', 'Rose Island – Goodies', 1013),
  ('route-green-parrot--junkanoo-beach', 'route', 'Junkanoo Beach', 'per_person', 1200, 2000, 'Green Parrot', 'Junkanoo Beach', 1014),
  ('route-green-parrot--arawak-cay-fish-fry', 'route', 'Arawak Cay / Fish Fry', 'per_person', 1600, 2800, 'Green Parrot', 'Arawak Cay / Fish Fry', 1015),
  ('route-green-parrot--goodman-s-bay', 'route', 'Goodman''s Bay', 'per_person', 4000, 7000, 'Green Parrot', 'Goodman''s Bay', 1016),
  ('route-green-parrot--breezes', 'route', 'Breezes', 'per_person', 4000, 7000, 'Green Parrot', 'Breezes', 1017),
  ('route-green-parrot--baha-mar', 'route', 'Baha Mar', 'per_person', 4500, 8000, 'Green Parrot', 'Baha Mar', 1018),
  ('route-poop-deck--pigs-beach', 'route', 'Pigs Beach', 'per_person', 2500, 4500, 'Poop Deck', 'Pigs Beach', 1019),
  ('route-poop-deck--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 3500, 6000, 'Poop Deck', 'Rose Island – Goodies', 1020),
  ('route-poop-deck--junkanoo-beach', 'route', 'Junkanoo Beach', 'per_person', 1600, 2800, 'Poop Deck', 'Junkanoo Beach', 1021),
  ('route-poop-deck--arawak-cay-fish-fry', 'route', 'Arawak Cay / Fish Fry', 'per_person', 2000, 3500, 'Poop Deck', 'Arawak Cay / Fish Fry', 1022),
  ('route-poop-deck--goodman-s-bay', 'route', 'Goodman''s Bay', 'per_person', 4000, 7000, 'Poop Deck', 'Goodman''s Bay', 1023),
  ('route-poop-deck--breezes', 'route', 'Breezes', 'per_person', 4000, 7000, 'Poop Deck', 'Breezes', 1024),
  ('route-poop-deck--baha-mar', 'route', 'Baha Mar', 'per_person', 4500, 8000, 'Poop Deck', 'Baha Mar', 1025)
on conflict (slug) do update set
  price_cents = excluded.price_cents, round_trip_cents = excluded.round_trip_cents,
  from_point = excluded.from_point, to_point = excluded.to_point, is_active = true;
