-- Stop-to-stop fares from Jack's sheet (Jack confirmed in chat, 5 Oct 2026: $10 one way, $18 round trip).
-- Per person, before VAT. Generated by scripts/import-fares.py.

insert into services
  (slug, category, title, pricing_model, price_cents, round_trip_cents, from_point, to_point, sort)
values
  ('route-poop-deck--fort-montagu', 'route', 'Fort Montagu', 'per_person', 1000, 1800, 'Poop Deck', 'Fort Montagu', 1000)
on conflict (slug) do update set
  price_cents = excluded.price_cents, round_trip_cents = excluded.round_trip_cents,
  from_point = excluded.from_point, to_point = excluded.to_point, is_active = true;
