-- Stop-to-stop fares from Jack's sheet (fares to fill v6, 5 Oct 2026: the last 15 pairs).
-- Per person, before VAT. Generated by scripts/import-fares.py.

insert into services
  (slug, category, title, pricing_model, price_cents, round_trip_cents, from_point, to_point, sort)
values
  ('route-fort-montagu--junkanoo-beach', 'route', 'Junkanoo Beach', 'per_person', 2000, 3500, 'Fort Montagu', 'Junkanoo Beach', 1000),
  ('route-fort-montagu--arawak-cay-fish-fry', 'route', 'Arawak Cay / Fish Fry', 'per_person', 2500, 4500, 'Fort Montagu', 'Arawak Cay / Fish Fry', 1001),
  ('route-fort-montagu--goodman-s-bay', 'route', 'Goodman''s Bay', 'per_person', 4000, 7000, 'Fort Montagu', 'Goodman''s Bay', 1002),
  ('route-fort-montagu--breezes', 'route', 'Breezes', 'per_person', 4000, 7000, 'Fort Montagu', 'Breezes', 1003),
  ('route-fort-montagu--baha-mar', 'route', 'Baha Mar', 'per_person', 4000, 7000, 'Fort Montagu', 'Baha Mar', 1004),
  ('route-junkanoo-beach--arawak-cay-fish-fry', 'route', 'Arawak Cay / Fish Fry', 'per_person', 1000, 1800, 'Junkanoo Beach', 'Arawak Cay / Fish Fry', 1005),
  ('route-junkanoo-beach--goodman-s-bay', 'route', 'Goodman''s Bay', 'per_person', 3000, 5000, 'Junkanoo Beach', 'Goodman''s Bay', 1006),
  ('route-junkanoo-beach--breezes', 'route', 'Breezes', 'per_person', 3000, 5000, 'Junkanoo Beach', 'Breezes', 1007),
  ('route-junkanoo-beach--baha-mar', 'route', 'Baha Mar', 'per_person', 3500, 6000, 'Junkanoo Beach', 'Baha Mar', 1008),
  ('route-arawak-cay-fish-fry--goodman-s-bay', 'route', 'Goodman''s Bay', 'per_person', 2500, 4500, 'Arawak Cay / Fish Fry', 'Goodman''s Bay', 1009),
  ('route-arawak-cay-fish-fry--breezes', 'route', 'Breezes', 'per_person', 2500, 4500, 'Arawak Cay / Fish Fry', 'Breezes', 1010),
  ('route-arawak-cay-fish-fry--baha-mar', 'route', 'Baha Mar', 'per_person', 3000, 5000, 'Arawak Cay / Fish Fry', 'Baha Mar', 1011),
  ('route-goodman-s-bay--breezes', 'route', 'Breezes', 'per_person', 1000, 1800, 'Goodman''s Bay', 'Breezes', 1012),
  ('route-goodman-s-bay--baha-mar', 'route', 'Baha Mar', 'per_person', 1000, 1800, 'Goodman''s Bay', 'Baha Mar', 1013),
  ('route-breezes--baha-mar', 'route', 'Baha Mar', 'per_person', 1000, 1800, 'Breezes', 'Baha Mar', 1014)
on conflict (slug) do update set
  price_cents = excluded.price_cents, round_trip_cents = excluded.round_trip_cents,
  from_point = excluded.from_point, to_point = excluded.to_point, is_active = true;
