-- Stop-to-stop fares from Jack's sheet (fares to drop-off stops, 5 Oct 2026: the last 39 trips).
-- Per person, before VAT. Generated by scripts/import-fares.py.

insert into services
  (slug, category, title, pricing_model, price_cents, round_trip_cents, from_point, to_point, sort)
values
  ('route-senor-frog-s--pearl-island', 'route', 'Pearl Island', 'per_person', 3000, 4900, 'Señor Frog''s', 'Pearl Island', 1000),
  ('route-senor-frog-s--floating-bar', 'route', 'Floating Bar', 'per_person', 2500, 4500, 'Señor Frog''s', 'Floating Bar', 1001),
  ('route-senor-frog-s--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 3500, 6000, 'Señor Frog''s', 'Blue Lagoon', 1002),
  ('route-green-parrot--pearl-island', 'route', 'Pearl Island', 'per_person', 3000, 5000, 'Green Parrot', 'Pearl Island', 1003),
  ('route-green-parrot--floating-bar', 'route', 'Floating Bar', 'per_person', 2500, 4500, 'Green Parrot', 'Floating Bar', 1004),
  ('route-green-parrot--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 3500, 6000, 'Green Parrot', 'Blue Lagoon', 1005),
  ('route-poop-deck--pearl-island', 'route', 'Pearl Island', 'per_person', 2500, 4500, 'Poop Deck', 'Pearl Island', 1006),
  ('route-poop-deck--floating-bar', 'route', 'Floating Bar', 'per_person', 2000, 3500, 'Poop Deck', 'Floating Bar', 1007),
  ('route-poop-deck--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 3000, 5000, 'Poop Deck', 'Blue Lagoon', 1008),
  ('route-fort-montagu--pearl-island', 'route', 'Pearl Island', 'per_person', 2500, 4500, 'Fort Montagu', 'Pearl Island', 1009),
  ('route-fort-montagu--floating-bar', 'route', 'Floating Bar', 'per_person', 2000, 3500, 'Fort Montagu', 'Floating Bar', 1010),
  ('route-fort-montagu--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 3000, 5000, 'Fort Montagu', 'Blue Lagoon', 1011),
  ('route-fort-montagu--pigs-beach', 'route', 'Pigs Beach', 'per_person', 2000, 3500, 'Fort Montagu', 'Pigs Beach', 1012),
  ('route-fort-montagu--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 3000, 5000, 'Fort Montagu', 'Rose Island – Goodies', 1013),
  ('route-junkanoo-beach--pearl-island', 'route', 'Pearl Island', 'per_person', 3000, 5000, 'Junkanoo Beach', 'Pearl Island', 1014),
  ('route-junkanoo-beach--floating-bar', 'route', 'Floating Bar', 'per_person', 2500, 4500, 'Junkanoo Beach', 'Floating Bar', 1015),
  ('route-junkanoo-beach--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 3500, 6000, 'Junkanoo Beach', 'Blue Lagoon', 1016),
  ('route-junkanoo-beach--pigs-beach', 'route', 'Pigs Beach', 'per_person', 2500, 4500, 'Junkanoo Beach', 'Pigs Beach', 1017),
  ('route-junkanoo-beach--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 3500, 6000, 'Junkanoo Beach', 'Rose Island – Goodies', 1018),
  ('route-arawak-cay-fish-fry--pearl-island', 'route', 'Pearl Island', 'per_person', 3500, 6000, 'Arawak Cay / Fish Fry', 'Pearl Island', 1019),
  ('route-arawak-cay-fish-fry--floating-bar', 'route', 'Floating Bar', 'per_person', 3000, 5000, 'Arawak Cay / Fish Fry', 'Floating Bar', 1020),
  ('route-arawak-cay-fish-fry--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 4000, 7000, 'Arawak Cay / Fish Fry', 'Blue Lagoon', 1021),
  ('route-arawak-cay-fish-fry--pigs-beach', 'route', 'Pigs Beach', 'per_person', 3000, 5000, 'Arawak Cay / Fish Fry', 'Pigs Beach', 1022),
  ('route-arawak-cay-fish-fry--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 4000, 7000, 'Arawak Cay / Fish Fry', 'Rose Island – Goodies', 1023),
  ('route-goodman-s-bay--pearl-island', 'route', 'Pearl Island', 'per_person', 4000, 7000, 'Goodman''s Bay', 'Pearl Island', 1024),
  ('route-goodman-s-bay--floating-bar', 'route', 'Floating Bar', 'per_person', 3500, 6000, 'Goodman''s Bay', 'Floating Bar', 1025),
  ('route-goodman-s-bay--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 4500, 8000, 'Goodman''s Bay', 'Blue Lagoon', 1026),
  ('route-goodman-s-bay--pigs-beach', 'route', 'Pigs Beach', 'per_person', 3500, 6000, 'Goodman''s Bay', 'Pigs Beach', 1027),
  ('route-goodman-s-bay--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 4500, 8000, 'Goodman''s Bay', 'Rose Island – Goodies', 1028),
  ('route-breezes--pearl-island', 'route', 'Pearl Island', 'per_person', 4000, 7000, 'Breezes', 'Pearl Island', 1029),
  ('route-breezes--floating-bar', 'route', 'Floating Bar', 'per_person', 3500, 6000, 'Breezes', 'Floating Bar', 1030),
  ('route-breezes--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 4500, 8000, 'Breezes', 'Blue Lagoon', 1031),
  ('route-breezes--pigs-beach', 'route', 'Pigs Beach', 'per_person', 3500, 6000, 'Breezes', 'Pigs Beach', 1032),
  ('route-breezes--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 4500, 8000, 'Breezes', 'Rose Island – Goodies', 1033),
  ('route-baha-mar--pearl-island', 'route', 'Pearl Island', 'per_person', 4500, 8000, 'Baha Mar', 'Pearl Island', 1034),
  ('route-baha-mar--floating-bar', 'route', 'Floating Bar', 'per_person', 4000, 7000, 'Baha Mar', 'Floating Bar', 1035),
  ('route-baha-mar--blue-lagoon', 'route', 'Blue Lagoon', 'per_person', 5000, 9000, 'Baha Mar', 'Blue Lagoon', 1036),
  ('route-baha-mar--pigs-beach', 'route', 'Pigs Beach', 'per_person', 4000, 7000, 'Baha Mar', 'Pigs Beach', 1037),
  ('route-baha-mar--rose-island-goodies', 'route', 'Rose Island – Goodies', 'per_person', 5000, 9000, 'Baha Mar', 'Rose Island – Goodies', 1038)
on conflict (slug) do update set
  price_cents = excluded.price_cents, round_trip_cents = excluded.round_trip_cents,
  from_point = excluded.from_point, to_point = excluded.to_point, is_active = true;
